# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1c74ba2f7d0f99ad454a713ed0853ed29d9b512bcaa71af081cb84d6d4d4ef92f0da6c8ce673b48ad168591b5749741b0d28430d2706b34951fce96c2b66c565

test:
  secret_key_base: 1453335291e06aa5838663ffed737e0413575eedfe1f6feb510b0529f0d573c9d71b151f86d52cefcd0a8b470a9e50af8a1b6fd93d3dff31a49fa1a4649f3f69

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
